### ISSUE TITLE
Site not found for docs

### ISSUE THREAD

**Issue by 0f4d0335** [dscc-admin-ch/lomas#114]
Hi all, the link to https://dscc-admin-ch.github.io/lomas-client-docs/ found in the arxiv article and README.md lead to a 404 page.

**Comment by 0f4d0335** [comment]
Yes, it appears the new site no longer results in the 404 error. And the old link works as intended.

**Comment by PaulineMauryL** [comment]
Yes, thanks again for letting us know! I put the old page back for future readers of the white paper after answering you.
